version: '3'

services:


  db:
    image: "postgres"
    ports:
      - 5436:5432
    hostname: lo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=marat
      - POSTGRES_PASSWORD=ab123
      - POSTGRES_DB=test_user_balances

    container_name: postgres


  app:

    build: .
    depends_on:
      - db

    volumes:
      - /e/All projects/Projects/go-rest-api:/app
    entrypoint: /bin/bash scripts/start_app.sh
    #    command:
    ports:
      - 7777:8080
    env_file:
      - ./.env





volumes:
  postgres-data: